RepositoryType=csvfile
PatientsPath=data/patients.csv
AppointmentsPath=data/appointments.csv



#RepositoryType=binaryfile
#PatientsPath=data/patients.bin
#AppointmentsPath=data/appointments.bin



#RepositoryType=database
#PatientsPath=jdbc:sqlite:A:/Iulia/Desktop/ubb/anul 2/java/a9-Iuliaa576/data/patients.sqlite
#AppointmentsPath=jdbc:sqlite:A:/Iulia/Desktop/ubb/anul 2/java/a9-Iuliaa576/data/appointments.sqlite



#RepositoryType=jsonfile
#PatientsPath=data/patients.json
#AppointmentsPath=data/appointments.json



#RepositoryType=xmlfile
#PatientsPath=data/patients.xml
#AppointmentsPath=data/appointments.xml